swagger: '2.0'
info:
  version: '0.1'
  title: Items API
  description: Manage menu items for a food cart.
host: artomatic-test.apigee.net
basePath: /v1/streetcarts
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/items/{item_id}':
    get:
      description: Lists menu item details.
      operationId: getItemById
      parameters:
        - name: item_id
          in: path
          description: ID of the menu item.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
    put:
      description: Updates a menu item.
      operationId: updateItemById
      parameters:
        - name: item_id
          in: path
          description: ID of the menu item.
          required: true
          type: string
        - name: body
          in: body
          required: true
          description: Updates for the menu item.
          schema:
            $ref: '#/definitions/updateItem'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
    delete:
      description: Deletes a menu item.
      operationId: deleteItemById
      parameters:
        - name: item_id
          in: path
          description: ID of the menu item.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
definitions:
  item:
    type: object
    properties:
      uuid:
        type: string
        description: ID of the menu item.
      cartID:
        type: string
        description: ID of the food cart.
      description:
        type: string
        description: Description of the menu item.
      itemName:
        type: string
        description: Name of the menu item.
      price:
        type: number
        description: Price of the menu item.
  updateItem:
    type: object
    properties:
      description:
        type: string
        description: Description of the menu item.
      itemName:
        type: string
        description: Name of the menu item.
      price:
        type: number
        description: Price of the menu item.
  UnauthorizedResponse:
    properties:
      message:
        type: string
