swagger: '2.0'
info:
  version: '0.1'
  title: Menus API
  description: Manage menus in your food cart.
host: artomatic-test.apigee.net
basePath: /v1/streetcarts
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/menus/{menu_id}':
    get:
      description: Lists menu details.
      operationId: getMenuById
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/menu'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
    delete:
      description: Deletes a menu.
      operationId: deleteMenuById
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/menu'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
  '/menus/{menu_id}/items':
    get:
      description: Lists all items on a menu.
      operationId: getItemsForMenu
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/items'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
  '/menus/{menu_id}/items/{item_id}':
    put:
      description: Adds an item to a menu.
      operationId: addItemToMenu
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
        - name: item_id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
    delete:
      description: Deletes an item from a menu.
      operationId: deleteItemFromMenu
      parameters:
        - name: menu_id
          in: path
          description: ID of the menu.
          required: true
          type: string
        - name: item_id
          in: path
          description: ID of the menu item.
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/item'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
definitions:
  menu:
    type: object
    properties:
      uuid:
        description: ID of the menu.
        type: string
      cartID:
        description: ID of the food cart.
        type: string
      menuName:
        type: string
        description: Name of the menu.
      items:
        type: array
        description: List of menu items.
        items:
          $ref: '#/definitions/item'
  items:
    type: array
    description: List of menu items.
    items:
      $ref: '#/definitions/item'
  item:
    type: object
    properties:
      uuid:
        type: string
        description: ID of the item.
      cartID:
        type: string
        description: ID of the food cart.
      description:
        type: string
        description: Description of the menu item.
      itemName:
        type: string
        description: Name of the menu item.
      price:
        type: number
        description: Price of the menu itme.
  UnauthorizedResponse:
    required:
      - message
    properties:
      message:
        type: string
